export const icons = {
	champagne: require("../assets/icons/champagne.png"),
	baby: require("../assets/icons/baby.png"),
	father: require("../assets/icons/father.png"),
	flags: require("../assets/icons/flags.png"),
	gift: require("../assets/icons/gift.png"),
	graduate: require("../assets/icons/graduate.png"),
	mother: require("../assets/icons/mother.png"),
	party: require("../assets/icons/party.png"),
	santa: require("../assets/icons/santa.png"),
	valentine: require("../assets/icons/valentine.png"),
	wedding: require("../assets/icons/wedding.png"),
	house: require("../assets/icons/house.png"),
	default: require("../assets/icons/default.png"),
};
