const produtos = [
	{
		id: 0,
		name: "Abajur",
		url: require("../assets/img/abajur.jpeg"),
		price: "79.90",
		description:
			"Que tal esse lindo abajur para iluminar a vida de alguem especial?",
	},
	{
		id: 1,
		name: "AirFryer",
		url: require("../assets/img/airfryer.jpeg"),
		price: "239.90",
		description: "Fazer um lanche rapido e saudavel quando for me visitar!",
	},
	{
		id: 2,
		name: "Conjunto de almofadas",
		url: require("../assets/img/almofadas.jpeg"),
		price: "69.90",
		description: "Deixar meu sofa mais bonito para te receber.",
	},
	{
		id: 3,
		name: "Armario",
		url: require("../assets/img/armario.jpeg"),
		price: "419.90",
		description: "Nada como organizar meus livros!",
	},
	{
		id: 4,
		name: "Aspirador de po",
		url: require("../assets/img/aspirador.jpeg"),
		price: "309.90",
		description: "Manter a casa sempre limpinha!",
	},
	{
		id: 5,
		name: "Conjunto de cabides",
		url: require("../assets/img/cabides.jpeg"),
		price: "45.90",
		description: "Preciso pendurar as roupas, ne?",
	},
	{
		id: 6,
		name: "Conjunto de cadeiras",
		url: require("../assets/img/cadeiras.jpeg"),
		price: "159.90",
		description: "Onde vamos sentar?",
	},
	{
		id: 7,
		name: "Cafeteira",
		url: require("../assets/img/cafeteira.jpeg"),
		price: "159.90",
		description: "Um bom cafezinho!",
	},
	{
		id: 8,
		name: "Cama de casal",
		url: require("../assets/img/cama.jpeg"),
		price: "1599.90",
		description: "Dormir e bom demais!",
	},
	{
		id: 9,
		name: "Conjunto de cestos",
		url: require("../assets/img/cestos.jpeg"),
		price: "199.90",
		description: "Bonitos ate para decorar.",
	},
	{
		id: 10,
		name: "Escorredor de louca",
		url: require("../assets/img/escorredor.jpeg"),
		price: "129.90",
		description: "Toda casa tem um escorredor",
	},
	{
		id: 11,
		name: "Conjunto de espatulas",
		url: require("../assets/img/espatulas.jpeg"),
		price: "29.90",
		description: "Hmmm... hamburguer na chapa! Precisa de espatula.",
	},
	{
		id: 12,
		name: "Estante",
		url: require("../assets/img/estante.jpeg"),
		price: "199.90",
		description: "Manter tudo organizado!",
	},
	{
		id: 13,
		name: "Headset",
		url: require("../assets/img/fone.jpeg"),
		price: "219.90",
		description: "Uma boa musica para relaxar!",
	},
	{
		id: 14,
		name: "Frigideira",
		url: require("../assets/img/frigideira.jpeg"),
		price: "59.90",
		description: "Preparado para um ovo frito?",
	},
	{
		id: 15,
		name: "Geladeira",
		url: require("../assets/img/geladeira.jpeg"),
		price: "899.90",
		description: "Sempre cheia, de preferencia!",
	},
	{
		id: 16,
		name: "100 reais",
		url: require("../assets/img/dinheiro.jpg"),
		price: "100.00",
		description: "",
	},
	{
		id: 17,
		name: "200 reais",
		url: require("../assets/img/dinheiro2.jpg"),
		price: "200.00",
		description: "",
	},
	{
		id: 18,
		name: "300 reais",
		url: require("../assets/img/dinheiro3.jpg"),
		price: "300.00",
		description: "",
	},
	{
		id: 19,
		name: "Câmera Instax",
		url: require("../assets/img/instax.jpeg"),
		price: "499.90",
		description: "",
	},
	{
		id: 20,
		name: "Jogo de Cama Casal",
		url: require("../assets/img/jogocama.jpeg"),
		price: "199.00",
		description: "",
	},
	{
		id: 21,
		name: "Jogo de colheres",
		url: require("../assets/img/jogocozinha.jpeg"),
		price: "219.90",
		description: "",
	},
	{
		id: 22,
		name: "Jogo de Cama Solteiro",
		url: require("../assets/img/lencol.jpeg"),
		price: "99.90",
		description: "",
	},
	{
		id: 23,
		name: "Liquidificador",
		url: require("../assets/img/liquidificador.jpeg"),
		price: "119.90",
		description: "",
	},
	{
		id: 24,
		name: "Lixeira Elétrica",
		url: require("../assets/img/lixeira.jpeg"),
		price: "259.90",
		description: "",
	},
	{
		id: 25,
		name: "Mala de viagem",
		url: require("../assets/img/mala.jpeg"),
		price: "199.90",
		description: "",
	},
	{
		id: 26,
		name: "Conjunto de malas",
		url: require("../assets/img/malas.jpeg"),
		price: "599.90",
		description: "",
	},
	{
		id: 27,
		name: "Microondas",
		url: require("../assets/img/microondas.jpeg"),
		price: "399.90",
		description: "",
	},
	{
		id: 28,
		name: "Nintendo Switch",
		url: require("../assets/img/nintendo.jpeg"),
		price: "2399.90",
		description: "",
	},
	{
		id: 29,
		name: "Notebook",
		url: require("../assets/img/notebook.jpeg"),
		price: "4199.90",
		description: "",
	},
	{
		id: 30,
		name: "Organizador",
		url: require("../assets/img/organizador.jpeg"),
		price: "129.90",
		description: "",
	},
	{
		id: 31,
		name: "Conjunto de panelas",
		url: require("../assets/img/panelas.jpeg"),
		price: "378.90",
		description: "",
	},
	{
		id: 32,
		name: "Conjunto de vasilhas",
		url: require("../assets/img/potes.jpeg"),
		price: "129.90",
		description: "",
	},
	{
		id: 33,
		name: "Sofá",
		url: require("../assets/img/sofa.jpeg"),
		price: "599.90",
		description: "",
	},
	{
		id: 34,
		name: "Conjunto de temperos",
		url: require("../assets/img/temperos.jpeg"),
		price: "149.99",
		description: "",
	},
	{
		id: 35,
		name: "Torradeira",
		url: require("../assets/img/torradeira.jpeg"),
		price: "199.90",
		description: "",
	},
	{
		id: 36,
		name: "Televisão",
		url: require("../assets/img/tv.jpeg"),
		price: "1599.90",
		description: "",
	},
	{
		id: 37,
		name: "Óculos de Realidade Virtual",
		url: require("../assets/img/vr.jpeg"),
		price: "2099.90",
		description: "",
	},
	{
		id: 38,
		name: "Smart Watch",
		url: require("../assets/img/watch.jpeg"),
		price: "1199.90",
		description: "",
	},
];

export default produtos;
